---

detectors:
  IrresponsibleModule:
    enabled: false

  ModuleInitialize:
    enabled: false

  BooleanParameter:
    exclude:
      - OnStrum::Service::InstanceMethods#respond_to_missing?

  FeatureEnvy:
    exclude:
      - OnStrum::Service::InstanceMethods#default_pro
      - OnStrum::Service::ClassMethods#call

  TooManyStatements:
    exclude:
      - OnStrum::Service::InstanceMethods#initialize
      - OnStrum::Service::InstanceMethods#execute

  UtilityFunction:
    exclude:
      - OnStrum::Service::InstanceMethods#method_s_sym
      - OnStrum::Service::InstanceMethods#from_input?
      - OnStrum::Service::InstanceMethods#from_inputs?

exclude_paths:
  - spec/support/helpers
